# Project information
site_name: "Sailfish Documentation"
# site_description: 'Sailfish Documentation'
site_author: "Ryohei Machida"
# site_url: 'https://***.com'

# Copyright
copyright: "&copy; 2020 Ryohei Machida"

# Repository
repo_name: "rust-sailfish/sailfish"
repo_url: "https://github.com/rust-sailfish/sailfish"

theme:
  name: "material"
  language: "en"
  logo: "images/logo.svg"
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: "dark"
      primary: "deep purple"
      accent: "deep purple"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Light Mode"
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "deep purple"
      accent: "deep purple"
      toggle:
        icon: "material/lightbulb"
        name: "Dark Mode"
  favicon: "images/favicon.ico"
  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"
  features:
    - "navigation.expand"

# Extensions
markdown_extensions:
  - "admonition"
  - "footnotes"
  - "pymdownx.highlight"
  - "pymdownx.tabbed":
      alternate_style: true
  - "pymdownx.superfences":
      custom_fences:
        - name: mermaid
          class: mermaid

extra_css:
  - "assets/css/custom.css"

extra:
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/rust-sailfish"

# Page tree
nav:
  - "Welcome": "index.md"
  - "Installation": "installation.md"
  - "Getting Started": "getting-started.md"
  - "Configuration": "options.md"
  - "Syntax":
      - "Overview": "syntax/overview.md"
      - "Tags": "syntax/tags.md"
      - "Includes": "syntax/includes.md"
      - "Filters": "syntax/filters.md"
